name: main
on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * 0"
jobs:
  cygwin:
    runs-on: windows-latest
    steps:
      - run: git config --global core.autocrlf input
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - uses: cygwin/cygwin-install-action@master
        with:
          packages: nc
      - run: python plano test
  fedora:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3
      - run: dnf -y install bats busybox curl dash ksh mksh nc python /bin/ps sudo tar yash zsh java-17-openjdk-headless
      - run: cd /usr/bin && ln -s busybox ash
      - run: ./plano test
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - run: brew install bats-core
      - run: ./plano test
  ubuntu:
    runs-on: ubuntu-latest
    container: ubuntu:latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get -qq update
      - run: apt-get -qq install bats curl netcat python3 sudo openjdk-17-jre-headless
      - run: ./plano test
